#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

app: 
    type: rest
    resource: "@AppBundle/Resources/config/apps_routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc